//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_DichVu
    {
        public int Id { get; set; }
        public int WorkId { get; set; }
        public int WorkTypeId { get; set; }
        public System.DateTime TimeProcess { get; set; }
        public double Price_In { get; set; }
        public double Price_Out { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual H_Work H_Work { get; set; }
        public virtual H_WorkType H_WorkType { get; set; }
    }
}
