//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_KhachHang
    {
        public H_KhachHang()
        {
            this.H_Receiption = new HashSet<H_Receiption>();
            this.H_SellReceipt = new HashSet<H_SellReceipt>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Wards { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public Nullable<int> JobId { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual H_NgheNghiep H_NgheNghiep { get; set; }
        public virtual ICollection<H_Receiption> H_Receiption { get; set; }
        public virtual ICollection<H_SellReceipt> H_SellReceipt { get; set; }
    }
}
