//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_KhachHang
    {
        public H_KhachHang()
        {
            this.H_Receipt = new HashSet<H_Receipt>();
        }
    
        public int Id { get; set; }
        public int ModelId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Wards { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Job { get; set; }
        public string Note { get; set; }
        public string MachineNumber { get; set; }
        public string ChassisNumber { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<int> Km { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual H_Model H_Model { get; set; }
        public virtual ICollection<H_Receipt> H_Receipt { get; set; }
    }
}
