//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_LoaiNhanVien
    {
        public H_LoaiNhanVien()
        {
            this.H_NhanVien = new HashSet<H_NhanVien>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<H_NhanVien> H_NhanVien { get; set; }
    }
}
