//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_NhapPT
    {
        public int Id { get; set; }
        public int PTId { get; set; }
        public string MaLo { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Quantities { get; set; }
        public double Price_In { get; set; }
        public double Price_Out { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual H_PhuTung H_PhuTung { get; set; }
    }
}
