//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_NhanVien
    {
        public H_NhanVien()
        {
            this.H_Receipt = new HashSet<H_Receipt>();
            this.H_Receipt1 = new HashSet<H_Receipt>();
            this.H_Receipt2 = new HashSet<H_Receipt>();
            this.H_Receipt3 = new HashSet<H_Receipt>();
            this.H_Receipt4 = new HashSet<H_Receipt>();
        }
    
        public int Id { get; set; }
        public int LoaiNVId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual H_LoaiNhanVien H_LoaiNhanVien { get; set; }
        public virtual ICollection<H_Receipt> H_Receipt { get; set; }
        public virtual ICollection<H_Receipt> H_Receipt1 { get; set; }
        public virtual ICollection<H_Receipt> H_Receipt2 { get; set; }
        public virtual ICollection<H_Receipt> H_Receipt3 { get; set; }
        public virtual ICollection<H_Receipt> H_Receipt4 { get; set; }
    }
}
