//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_NhanVien
    {
        public H_NhanVien()
        {
            this.H_Account = new HashSet<H_Account>();
            this.H_Receiption = new HashSet<H_Receiption>();
            this.H_Receiption1 = new HashSet<H_Receiption>();
            this.H_Receiption2 = new HashSet<H_Receiption>();
            this.H_Receiption3 = new HashSet<H_Receiption>();
            this.H_Receiption4 = new HashSet<H_Receiption>();
            this.H_SellReceipt = new HashSet<H_SellReceipt>();
        }
    
        public int Id { get; set; }
        public int LoaiNVId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int Index { get; set; }
    
        public virtual ICollection<H_Account> H_Account { get; set; }
        public virtual H_LoaiNhanVien H_LoaiNhanVien { get; set; }
        public virtual ICollection<H_Receiption> H_Receiption { get; set; }
        public virtual ICollection<H_Receiption> H_Receiption1 { get; set; }
        public virtual ICollection<H_Receiption> H_Receiption2 { get; set; }
        public virtual ICollection<H_Receiption> H_Receiption3 { get; set; }
        public virtual ICollection<H_Receiption> H_Receiption4 { get; set; }
        public virtual ICollection<H_SellReceipt> H_SellReceipt { get; set; }
    }
}
