//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_PhuTung
    {
        public H_PhuTung()
        {
            this.H_Receipt_PT = new HashSet<H_Receipt_PT>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Quantities { get; set; }
        public double Price_In { get; set; }
        public double Price_Out { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<H_Receipt_PT> H_Receipt_PT { get; set; }
    }
}
