//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_Receipt_PT
    {
        public int Id { get; set; }
        public int ReceiptId { get; set; }
        public int PT_Id { get; set; }
        public int Index { get; set; }
        public int Quantities { get; set; }
        public double Price { get; set; }
        public double Percent { get; set; }
        public double PricePercent { get; set; }
        public double Total { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual H_PhuTung H_PhuTung { get; set; }
        public virtual H_Receiption H_Receiption { get; set; }
    }
}
