//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_Receipt
    {
        public H_Receipt()
        {
            this.H_Receipt_PT = new HashSet<H_Receipt_PT>();
        }
    
        public int Id { get; set; }
        public int KHId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Code { get; set; }
        public Nullable<int> NV_TiepNhan { get; set; }
        public Nullable<int> NV_SuaXe { get; set; }
        public Nullable<int> NV_ThuNgan { get; set; }
        public Nullable<int> NV_KTTruong { get; set; }
        public Nullable<int> NV_KTCuoi { get; set; }
        public string Required { get; set; }
        public string CheckResult { get; set; }
        public string StatusBefore { get; set; }
        public int QMSNumber { get; set; }
        public int Old_Km { get; set; }
        public int New_Km { get; set; }
        public double Total { get; set; }
        public double Total_Cong { get; set; }
        public double Total_PTung { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<H_Receipt_PT> H_Receipt_PT { get; set; }
        public virtual H_NhanVien H_NhanVien { get; set; }
        public virtual H_NhanVien H_NhanVien1 { get; set; }
        public virtual H_NhanVien H_NhanVien2 { get; set; }
        public virtual H_NhanVien H_NhanVien3 { get; set; }
        public virtual H_NhanVien H_NhanVien4 { get; set; }
        public virtual H_KhachHang H_KhachHang { get; set; }
    }
}
