//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_WorkType
    {
        public H_WorkType()
        {
            this.H_DichVu = new HashSet<H_DichVu>();
            this.H_Receiption = new HashSet<H_Receiption>();
            this.H_SellReceipt = new HashSet<H_SellReceipt>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<H_DichVu> H_DichVu { get; set; }
        public virtual ICollection<H_Receiption> H_Receiption { get; set; }
        public virtual ICollection<H_SellReceipt> H_SellReceipt { get; set; }
    }
}
